# Site settings
title: Kirsten Walsh
email: kirsten.i.walsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirstenwalsh.me" # the base hostname & protocol for your site

# User setting
owner: Kirsten Walsh
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
